In [1]:
"""
Numpy arrays
"""

import numpy as np

p = np.array([48.858598, 2.294495])
print(p.ndim)
print(p.shape)
print(p.dtype)

# Data type
a = np.array([1, 2, 3, 4])
print(a.dtype)

float_b = a.astype(np.float64)
print(float_b.dtype)

# Array creation
a = np.arange(7)
print(a)
print(a[1], a[4], a[-1])

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[0, 2])

a[0, 2] = 10
print(a)

b = a[2]
print(b)

c = a[:2]
print(c)

b[-1] = 11
print(a)

# Fancy indexing
a = np.array([3, 5, 1, 10])
b = (a % 5 == 0)
print(b)

c = np.array([[0, 1], [2, 3], [4, 5], [6, 7]])
print(c[b])

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(a[[2, 1]])
print(a[[-2, -1]])
print(a[[2, 3], [0, 1]])

# Numerical operations on arrays
a = np.ones(4)
print(a * 2)
print(a + 3)

a = np.ones([2, 4])
print(a * a)
print(a + a)

a = np.array([1, 2, 3, 4])
b = np.array([1, 1, 5, 3])

print(a == b)
print(np.array_equal(a, b))

c = np.array([1, 0])
d = np.array([1, 1])
print(np.logical_and(c, d))

# Array functions
a = np.array([[0, 5, 10], [20, 25, 30]])
print(a.reshape(3, 2))
print(a.T)

a = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
print(a.swapaxes(1, 2))

a = np.array([[1, 2, 3],[4,5,6]])
print(np.dot(a.T, a))

a = np.array ([[6, 34, 1, 6], [0, 5, 2, -1]])
print(np.sort(a))
print(np.sort(a, axis=0))

b = np.argsort(a)
print(b)
print(a[0][b[0]])
print(np.argmax(a))

1
(2,)
float64
int64
float64
[0 1 2 3 4 5 6]
1 4 6
3
[[ 1  2 10]
 [ 4  5  6]
 [ 7  8  9]]
[7 8 9]
[[ 1  2 10]
 [ 4  5  6]]
[[ 1  2 10]
 [ 4  5  6]
 [ 7  8 11]]
[False  True False  True]
[[2 3]
 [6 7]]
[[ 9 10 11 12]
 [ 5  6  7  8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[ 9 14]
[2. 2. 2. 2.]
[4. 4. 4. 4.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[ True False False False]
False
[ True False]
[[ 0  5]
 [10 20]
 [25 30]]
[[ 0 20]
 [ 5 25]
 [10 30]]
[[[ 0  3]
  [ 1  4]
  [ 2  5]]

 [[ 6  9]
  [ 7 10]
  [ 8 11]]]
[[17 22 27]
 [22 29 36]
 [27 36 45]]
[[ 1  6  6 34]
 [-1  0  2  5]]
[[ 0  5  1 -1]
 [ 6 34  2  6]]
[[2 0 3 1]
 [3 0 2 1]]
[ 1  6  6 34]
1
